/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vksv;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

/**
 *
 * @author kmangl
 */
public class EmployeeDetails extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeDetails
     */
    public EmployeeDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmployeeID = new javax.swing.JLabel();
        lblEmployeeName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        txtEmployeeName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        btnFindbyID = new javax.swing.JButton();
        btnEmployeeName = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblSalary = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEmployeeID.setText("Employee ID");
        lblEmployeeID.setToolTipText("");

        lblEmployeeName.setText("Emloyee Name");

        lblLastName.setText("Last Name");

        btnFindbyID.setText("FindbyID");
        btnFindbyID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindbyIDActionPerformed(evt);
            }
        });

        btnEmployeeName.setText("EmployeeName");
        btnEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeNameActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblSalary.setText("Salary");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmployeeID)
                            .addComponent(lblEmployeeName)
                            .addComponent(lblLastName)
                            .addComponent(lblSalary))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmployeeID, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(txtEmployeeName)
                            .addComponent(txtLastName)
                            .addComponent(jTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnFindbyID)
                        .addGap(18, 18, 18)
                        .addComponent(btnEmployeeName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeID)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeName)
                    .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalary)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindbyID)
                    .addComponent(btnEmployeeName)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindbyIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindbyIDActionPerformed
        // TODO add your handling code here:
    	Connection dbConnection=null;
    	PreparedStatement pStatement=null;
    	try {
			DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
			
			//Establish a connection
			
			dbConnection=DriverManager.getConnection("jdbc:oracle:thin:@deltahiti31202:1521:XE","KRISHAN", "password");
			
			//Execute the query
			pStatement=dbConnection.prepareStatement("SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID=?");
			pStatement.setInt(1, Integer.parseInt(txtEmployeeID.getText()));
			ResultSet result=pStatement.executeQuery();
			if(result.next())
			{
				txtEmployeeName.setText(result.getString(1));
				txtLastName.setText(result.getString(2));
			}
			else
			{
				JOptionPane.showMessageDialog(this, "No record Found","Employee ID does not exist",JOptionPane.ERROR_MESSAGE);
			}
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	finally{
    		try {
				if(dbConnection!=null &&!dbConnection.isClosed()){
					dbConnection.close();
				}
				if(pStatement!=null ){
					pStatement.close();
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
    	}
    }//GEN-LAST:event_btnFindbyIDActionPerformed

    private void btnEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeNameActionPerformed
        // TODO add your handling code here:
    	Connection dbConnection=null;
    	PreparedStatement pStatement=null;
    	try {
			DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
			
			//Establish a connection
			
			dbConnection=DriverManager.getConnection("jdbc:oracle:thin:@deltahiti31202:1521:XE","KRISHAN", "password");
			
			//Execute the query
			pStatement=dbConnection.prepareStatement("UPDATE DUPLICATE SET FIRST_NAME=?,LAST_NAME=?WHERE EMP_ID=?");
			pStatement.setInt(3, Integer.parseInt(txtEmployeeID.getText()));
			pStatement.setString(1, txtEmployeeName.getText());
			pStatement.setString(2, txtLastName.getText());
			int result=pStatement.executeUpdate();
			if(result!=0)
			{
				JOptionPane.showMessageDialog(this, " Updated","Employee ID Inserted",JOptionPane.PLAIN_MESSAGE);
			}
			else
			{
				JOptionPane.showMessageDialog(this, "No record Found","Employee ID does not exist",JOptionPane.ERROR_MESSAGE);
			}
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	finally{
    		try {
				if(dbConnection!=null &&!dbConnection.isClosed()){
					dbConnection.close();
				}
				if(pStatement!=null ){
					pStatement.close();
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
    	}
    	
    	
    }//GEN-LAST:event_btnEmployeeNameActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    	Connection dbConnection=null;
    	PreparedStatement pStatement=null;
    	try {
			DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
			
			//Establish a connection
			
			dbConnection=DriverManager.getConnection("jdbc:oracle:thin:@deltahiti31202:1521:XE","KRISHAN", "password");
			
			//Execute the query
			pStatement=dbConnection.prepareStatement("INSERT INTO DUPLICATE VALUES(?,?,?)");
			pStatement.setInt(1, Integer.parseInt(txtEmployeeID.getText()));
			pStatement.setString(2, txtEmployeeName.getText());
			pStatement.setString(3, txtLastName.getText());
			int result=pStatement.executeUpdate();
			if(result!=0)
			{
				JOptionPane.showMessageDialog(this, " Updated","Employee ID Inserted",JOptionPane.PLAIN_MESSAGE);
			}
			else
			{
				JOptionPane.showMessageDialog(this, "No record Found","Employee ID does not exist",JOptionPane.ERROR_MESSAGE);
			}
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	finally{
    		try {
				if(dbConnection!=null &&!dbConnection.isClosed()){
					dbConnection.close();
				}
				if(pStatement!=null ){
					pStatement.close();
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
    	}
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    	Connection dbConnection=null;
    	PreparedStatement pStatement=null;
    	try {
			DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
			
			//Establish a connection
			
			dbConnection=DriverManager.getConnection("jdbc:oracle:thin:@deltahiti31202:1521:XE","KRISHAN", "password");
			
			//Execute the query
			pStatement=dbConnection.prepareStatement("DELETE  FROM EMPLOYEES WHERE EMPLOYEE_ID=?");
			pStatement.setInt(1, Integer.parseInt(txtEmployeeID.getText()));
			int result=pStatement.executeUpdate();
			if(result!=0)
			{
				JOptionPane.showMessageDialog(this, " record Found","Employee ID exist",JOptionPane.PLAIN_MESSAGE);
			}
			else
			{
				JOptionPane.showMessageDialog(this, "No record Found","Employee ID does not exist",JOptionPane.ERROR_MESSAGE);
			}
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	finally{
    		try {
				if(dbConnection!=null &&!dbConnection.isClosed()){
					dbConnection.close();
				}
				if(pStatement!=null ){
					pStatement.close();
				}
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
    	}
    	
    	
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEmployeeName;
    private javax.swing.JButton btnFindbyID;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtEmployeeName;
    private javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables
}
